# This workflow will run tests using bun and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: BunJS Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: "https://npm.pkg.github.com/"
      - run: bun install --frozen-lockfile
      - run: bun test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: "https://npm.pkg.github.com/"
      - run: bun install
      - run: bun publish
        env:
          BUN_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
